title: Unload Brain
author: Mossaddeque Mahmood
email: mmahmood.ict.bd[at]gmail.com
description: Uploading my brain dump.

baseurl: "" 
url: "https://unloadbrain.com"
twitter_username: mmahmood_ict_bd
github_username:  mmahmoodictbd
show_excerpts: true
google_analytics: UA-121247298-1

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap

minima:
  timezone: Europe/Amsterdam
  social_links:
    twitter: mmahmood_ict_bd
    github: mmahmoodictbd
    linkedin: mmahmoodictbd
    keybase: mmahmoodictbd
    rss: rss

jekyll-archives:
  enabled: ['categories', 'tags', 'year']
  permalinks:
    year: '/:year/'
    tag: '/tag/:name/'
    category: '/category/:name/'
  layouts:
    year: year-archive
    category: category-archive
    tag: tag-archive