title: Unload Brain
email: mmahmood.ict.bd@gmail.com
description: >-
  Mossaddeque Mahmood, Technology evangelist, Clean Coder, 
  a passionate full-stack developer with a great understanding 
  of Java, Enterprise Application, Microservice, and DevOps.
baseurl: "" 
url: "http://unloadbrain.com"
twitter_username: mmahmood_ict_bd
github_username:  mmahmoodictbd

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  timezone: Europe/Amsterdam
  social_links:
    twitter: mmahmood_ict_bd
    github: mmahmoodictbd
    linkedin: mmahmoodictbd
    keybase: mossaddeque
    rss: rss


