name: chumbok_apps
description: Chumbok Apps

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

platforms:
  android:

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter:
  http:
  logger:
  html:
  url_launcher: ^6.1.9
  provider: ^6.0.5
  cupertino_icons: ^1.0.0
  auto_size_text: ^3.0.0
  firebase_core: ^2.6.1
  firebase_analytics: ^10.1.3
  yaml: ^3.1.1
  synchronized: ^3.0.1
  json_theme: ^4.0.0
  settings_ui: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.18

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/common/config/
    - assets/kobita_app/config/
    - assets/kobita_app/images/
    - assets/kobita_app/appainter_theme.json
    - assets/history_app/config/
    - assets/history_app/images/
